# Generated by Django 4.2.27 on 2025-12-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('processing', 'Processing (Inventory)'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
