# Generated by Django 4.2 on 2025-12-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('recency', models.IntegerField(help_text='Days since last purchase')),
                ('frequency', models.IntegerField(help_text='Total number of orders')),
                ('monetary', models.DecimalField(decimal_places=2, help_text='Total spend', max_digits=12)),
                ('r_score', models.IntegerField()),
                ('f_score', models.IntegerField()),
                ('m_score', models.IntegerField()),
                ('segment_label', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='customersegmentation',
            index=models.Index(fields=['customer_email'], name='crm_opt_cus_custome_c22c25_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegmentation',
            index=models.Index(fields=['segment_label'], name='crm_opt_cus_segment_768c58_idx'),
        ),
    ]
