# Generated by Django 4.2 on 2025-12-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.UUIDField()),
                ('branch_id', models.UUIDField(blank=True, null=True)),
                ('current_stock', models.IntegerField()),
                ('avg_daily_consumption', models.FloatField()),
                ('suggested_reorder_point', models.IntegerField()),
                ('suggested_reorder_qty', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='inventoryoptimization',
            index=models.Index(fields=['product_uuid', 'branch_id'], name='inventory_o_product_32e237_idx'),
        ),
    ]
