# Generated by Django 4.2.27 on 2025-12-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_payment_emi_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='default_tax_zone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
