# Generated by Django 4.2.27 on 2025-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_possettings_default_tax_zone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('on_emi', 'On EMI'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
