# Generated by Django 4.2.27 on 2025-12-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
