# Generated by Django 4.2 on 2025-12-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_uuid', models.UUIDField(unique=True)),
                ('risk_score', models.FloatField(help_text='Probability of leaving (0-1)')),
                ('risk_level', models.CharField(max_length=20)),
                ('avg_monthly_hours', models.IntegerField(null=True)),
                ('absenteeism_rate', models.FloatField(null=True)),
                ('last_evaluation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='attritionprediction',
            index=models.Index(fields=['risk_level'], name='hr_opt_attr_risk_le_30586a_idx'),
        ),
    ]
