# Generated by Django 4.2 on 2025-12-06 23:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_company_uuid', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('tax_number', models.CharField(blank=True, max_length=128, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bin_number', models.CharField(blank=True, max_length=128, null=True)),
                ('accounting_codes', models.JSONField(blank=True, default=dict)),
                ('default_payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=20)),
                ('is_base', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('pos_printer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pos_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='tenants.company')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('order', models.IntegerField(default=0)),
                ('permission_code', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='tenants.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tenants.navigationitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=20)),
                ('next_invoice_number', models.BigIntegerField(default=1)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('detailed', 'Detailed')], default='standard', max_length=32)),
                ('footer_note', models.TextField(blank=True)),
                ('sequence_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='tenants.company')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.UUIDField(blank=True, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.company')),
            ],
            options={
                'ordering': ['-date_joined', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.CharField(blank=True, max_length=255, null=True)),
                ('nav', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['auth_company_uuid'], name='tenants_com_auth_co_7d9765_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wing',
            unique_together={('company', 'code')},
        ),
    ]
