# Generated by Django 4.2.27 on 2025-12-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailyproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='wing_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='wing_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproduction',
            unique_together={('company_uuid', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysales',
            unique_together={('company_uuid', 'wing_uuid', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='topproduct',
            unique_together={('company_uuid', 'wing_uuid', 'product_name')},
        ),
    ]
