# Generated by Django 4.2.26 on 2025-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
