# Generated by Django 4.2.27 on 2026-01-01 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_journalentry_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('purpose', models.CharField(choices=[('sales_revenue', 'Sales Revenue'), ('cash_on_hand', 'Cash on Hand'), ('sales_tax_payable', 'Sales Tax Payable'), ('depreciation_expense', 'Depreciation Expense'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('inventory', 'Inventory Assets'), ('cost_of_goods_sold', 'Cost of Goods Sold')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.chartofaccount')),
            ],
            options={
                'unique_together': {('company_uuid', 'purpose')},
            },
        ),
    ]
