# Generated by Django 4.2.27 on 2026-01-03 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_accountgroup_created_by_accountgroup_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('pos', 'Point of Sale'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('other', 'Other')], db_index=True, default='manual', max_length=50),
        ),
    ]
