# Generated by Django 4.2 on 2025-12-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_sales', models.FloatField()),
                ('confidence_lower', models.FloatField(null=True)),
                ('confidence_upper', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['date'], name='forecasts_s_date_a20697_idx'),
        ),
    ]
