# Generated by Django 4.2.27 on 2025-12-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='module_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('service', 'Service'), ('booking', 'Booking'), ('rental', 'Rental'), ('medical', 'Medical'), ('consultancy', 'Consultancy'), ('manufacturing', 'Manufacturing')], default='retail', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assigned_staff_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('rental', 'Rental'), ('fee', 'Fee'), ('package', 'Package')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
